version: '3.8'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:${DB_PORT}"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"
  mongo:
    image: mongo:latest
    ports:
      - "27017:${MONGO_PORT}"
  backend:
    build:
      context: ./backend
      dockerfile: server.Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - "./backend:/app"
    depends_on:
      - mysql
    links:
      - "mysql:database"
    restart: always
  prometheus:
    image: prom/prometheus:v2.40.4
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
    volumes:
      - ./backend/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
    depends_on:
      - prometheus
    links:
      - "prometheus:prometheus"
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${FRONTEND_PORT}:${FRONTEND_PORT}"
  #   volumes:
  #     - "./frontend:/app"
  #   restart: always

  # healthcheck:
  #   image: docker/compose:latest
  #   depends_on:
  #     - backend
  # make requests to the backend until it responds
  #   command: ["sh", "-c", "while ! curl -s http://backend:${SERVER_PORT}; do sleep 1; done"]
  #   restart: on-failure