version: '3.8'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:${DB_PORT}"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"
  mongo:
    image: mongo:latest
    ports:
      - "27017:${MONGO_PORT}"
  backend:
    build:
      context: ./backend
      dockerfile: server.Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - "./backend:/app"
    depends_on:
      - mysql
    links:
      - "mysql:database"
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: web.Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - "./frontend:/app"
    restart: always
