version: '3.8'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:${DB_PORT}"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"
  backend:
    build: 
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ".:/app"
    depends_on:
      - mysql
    links:
      - "mysql:database"
    restart: always
